CREATE TABLE drivers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    phone         VARCHAR(15)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    location_x    DOUBLE PRECISION,
    location_y    DOUBLE PRECISION
);

CREATE TABLE vehicles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make_model    VARCHAR(255) NOT NULL,
    license_plate VARCHAR(20)  NOT NULL UNIQUE
);

CREATE TABLE assignments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id  BIGINT      NOT NULL REFERENCES drivers (id) ON DELETE CASCADE,
    vehicle_id BIGINT      NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    start_time TIMESTAMP   NOT NULL,
    end_time   TIMESTAMP   NOT NULL,
    status     VARCHAR(10) NOT NULL DEFAULT 'SENT',
    CONSTRAINT chk_assignment_window CHECK (end_time > start_time),
    CONSTRAINT chk_assignment_status CHECK (status IN ('SENT', 'ACCEPTED', 'REJECTED'))
);

CREATE INDEX idx_assignments_driver ON assignments (driver_id, start_time);
CREATE INDEX idx_assignments_vehicle ON assignments (vehicle_id, start_time);
