# Generated by Django 4.2.15 on 2024-08-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_alter_driver_email_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='driver_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
